version: 2.1

# -------------------------
#         DEFAULTS
# -------------------------

workspace_root: &workspace_root ~/repo

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: cimg/node:15.11.0
  resource_class: large
cache_key: &cache_key v2-dependencies-{{ checksum "yarn.lock" }}

# -------------------------
#        WORKFLOWS
# -------------------------
workflows:
  build_and_test:
    jobs:
      - test
      - chromatic:
          requires:
            - test
      - release:
          requires:
            - test

# -------------------------
#          JOBS
# -------------------------
jobs:
  # Test and lint against the repo
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: *cache_key
          paths:
            - ./node_modules

      - run:
          name: Lint Code
          command: yarn lint:eslint .

      - run:
          name: Check Formatting
          command: yarn lint:prettier:check .

      - run:
          name: Run Tests
          command: yarn test

  # Build for Chromatic
  chromatic:
    <<: *defaults

    docker:
      - image: cimg/node:15.8.0-browsers

    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run:
          name: Build Storybook
          command: yarn storybook:build

      - run:
          name: Build Storybook Composition Cache
          command: yarn sb extract

      - run:
          name: Release Package
          command: npx semantic-release || true

      - run:
          name: Push to Chromatic
          command: yarn chromatic --project-token ${CHROMATIC_PROJECT_TOKEN} --exit-once-uploaded --storybook-build-dir ./storybook-static

  # Build for Chromatic
  release:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run:
          name: Build Package
          command: yarn build

      - run:
          name: Release Package
          command: npx semantic-release || true
