# CircleCI

version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies--{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint Code
          command: yarn fmt:eslint

      - run:
          name: Check Formatting
          command: yarn fmt:prettier:check

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Build Storybook
          command: yarn storybook:build

      - run:
          name: Push to Chromatic
          command: yarn chromatic --project-token ${CHROMATIC_PROJECT_TOKEN} --exit-once-uploaded --storybook-build-dir ./storybook-static
